// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "hal.h"
#include "mongoose_glue.h"

int main(void) {
  // Cross-platform hardware init
  hal_init();

  // This function blocks forever. Call it at the end of main(), or in a
  // separate RTOS task. Give that task 8k stack space.
  run_mongoose();

  return 0;
}
