# Generated by Mongoose Wizard - Makefile for Windows, Mac, Linux
# Environment setup: https://mongoose.ws/documentation/tutorials/tools/

SOURCES = main.c mongoose.c mongoose_fs.c mongoose_glue.c mongoose_impl.c
CFLAGS = -W -Wall -Wextra -Werror -Wundef -Wshadow -g3 -O0 -I.
CFLAGS += -Wno-cast-function-type
MFLAGS = -DMG_DATA_SIZE=64 -DMG_ENABLE_PACKED_FS=1 -DMG_TLS=MG_TLS_BUILTIN

# Build program from sources
build: $(SOURCES)
	$(CC) $(SOURCES) $(CFLAGS) $(MFLAGS) $(CFLAGS_EXTRA) -o firmware
	cp firmware firmware.bin

windows: $(PROG)
	cl /MD /Os /W3 /nologo $(SOURCES) $(MFLAGS) $(CFLAGS_EXTRA) /Fefirmware.exe
	copy firmware.exe firmware.bin
