// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Include your device-specific headers, and edit functions below
// #include "hal.h"

#include "mongoose_glue.h"

void glue_init(void) {
  MG_DEBUG(("Custom init done"));
}

static struct time s_time = {"10:23"};
struct time *glue_get_time(void) {
  return &s_time;  // Sync with your device
}
void glue_set_time(struct time *update) {
  s_time = *update; // Sync with your device
}